### ISSUE TITLE
NextJS 12 breaks useMutation usage

### ISSUE THREAD

**Issue by felquis** [gqty-dev/gqty#292] opened 2021-11-06 13:35 UTC
I have this component that use to work just fine with nextjs 11
```js
const DeleteAccount = () => {
  const [deleteAccount] = useMutation((mutation) => {
    const data = mutation.deleteUser();

    return { ...data };
  });
})
```

Once I updated the project to `yarn add next@12` it started throwing 
```txt
Unhandled Runtime Error
TypeError: (0 , _gqtyWEBPACK_IMPORTED_MODULE_3.useMutation) is not a function
```

Rolling back to nextjs 11 the issue disappear.

**Comment by vicary** [comment] 2021-11-06 14:08
Next 12 has no significant update for builds EXCEPT the removal of the deprecated webpack 4.

Are you using webpack 4 configs in your `next.config.js`?

**Comment by PabloSzx** [comment] 2021-11-06 16:18
> Next 12 has no significant update for builds EXCEPT the removal of the deprecated webpack 4.
> 
> Are you using webpack 4 configs in your `next.config.js`?

Yeah, we need an answer to that question AND a reproduction repo, all the examples/manual tests of gqty are using Next.js v12 with webpack 5

**Comment by felquis** [comment] 2021-11-06 18:26
Answering https://github.com/gqty-dev/gqty/issues/292#issuecomment-962457071

When using nextjs 11 the output is:
```
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
```

My next.config.js is:
```
module.exports = {
  reactStrictMode: true,
  env: {
    GRAPHQL_ENDPOINT: process.env.GRAPHQL_ENDPOINT
  }
}
```

If I `yarn add next@latest` it breaks with the run time errors. Anyways. I'll look further. Thanks.

**Comment by PabloSzx** [comment] 2021-11-06 18:28
It doesn't need to be closed if your issue is still there, it's just that we need a reproduction

**Comment by dan2kx** [comment] 2021-11-29 21:41
Here is a reproduction which was based on your nextjs example, i've bumped the deps for next and gqty to the latest.

i think it may just be a server-side error, i'm having it using resolved in getStaticProps

https://codesandbox.io/s/gqty-sandbox-forked-dwk3l?file=/src/pages/index.tsx:1468-1476

**Comment by PabloSzx** [comment] 2021-11-29 22:47
> Here is a reproduction which was based on your nextjs example, i've bumped the deps for next and gqty to the latest.
> 
> i think it may just be a server-side error, i'm having it using resolved in getStaticProps
> 
> https://codesandbox.io/s/gqty-sandbox-forked-dwk3l?file=/src/pages/index.tsx:1468-1476

thank you, I will take a look into it

**Comment by PabloSzx** [comment] 2021-11-29 22:59
Good and bad news, it seems like Next.js 12 broke the "export const { ..." syntax, this fixes everything:

![image](https://user-images.githubusercontent.com/8672915/143955836-39298ad2-ff15-4348-9e4e-f546c37ddee2.png)


but already generated clients won't be able to get this fix retroactively, something that can be done is analyze the already generated clients and print a warning to change the export syntax

**Comment by dan2kx** [comment] 2021-11-29 23:09
Cool, i can live with making that change myself, it seems to be working now thanks!

**Closed** 2021-11-29 23:57 UTC
Labels: invalid, reproduction-needed
