### ISSUE TITLE
Cache using wrong query

### ISSUE THREAD

**Issue by humet** [gqty-dev/gqty#896] opened 2022-05-30 14:18 UTC
I have an issue where GQTY is using the wrong query for fetching data. This then obviously returns the wrong data. From my investigations it looks as if it uses the incorrect cached query. 

I have create a minimal repo here: https://github.com/Dexerto/gqty-query-test 

To reproduce the error:

- Clone repo
- `cd gqty-query-test`
- `cp .env.local.sample .env.local`
- In `.env.local` change `NEXT_PUBLIC_WORDPRESS_URL` to `https://newstaging.dexerto.com`
- Run `npm install`
- Run `npm run build`
- Run `npm run start`
- Visit http://localhost:3000/
- Click 'Among Us` - note all posts have 'Among Us' in brackets. This is correct data.
- Click 'Guides' - There should now be 4 posts and no 'More Posts' button. Note all posts have 'Among Us' in brackets. This is correct data.
- Click 'News' - note all posts have 'Among Us' in brackets. This is correct data.
- Click 'Home' to return to home page.
- Click 'Animal Crossing - note all posts have 'Animal Crossing' in brackets. This is correct data.
- Click 'Guides' - note all posts have 'Among Us' in brackets. This is **incorrect** data.
- Click 'News' - note all posts have 'Among Us' in brackets. This is **incorrect** data.
- Click 'Home' to return to home page.
- Click 'Among Us` - note all posts have 'Among Us' in brackets. This is correct data.
- Scroll down and click 'More Posts' - note this loads in posts with 'Animal Crossing' in brackets. This is **incorrect** data.

**Comment by PabloSzx** [comment] 2022-06-08 17:06
![image](https://user-images.githubusercontent.com/8672915/172675242-f6cf02bc-ab2a-4ba9-a9f6-0191357c6b3a.png)
I get this error on the reproduction

and when ignoring typescript errors

![image](https://user-images.githubusercontent.com/8672915/172675284-8fbef83c-ac49-4450-989d-1915c8d679c0.png)

![image](https://user-images.githubusercontent.com/8672915/172675570-2e2bf2e1-b7f9-46ce-879d-81c832504729.png)

**Comment by PabloSzx** [comment] 2022-06-09 18:19
it's very weird that not even node-linker=hoisted fixes it, that literally does the same thing as npm, looking into it

**Comment by PabloSzx** [comment] 2022-06-20 02:43
ok, so I narrowed down the issue, it seems to be related with ssr hydration

**Comment by PabloSzx** [comment] 2022-06-20 04:54
Could you please confirm if your issue is fixed with https://github.com/Dexerto/gqty-query-test/pull/1

**Comment by humet** [comment] 2022-06-20 10:35
Hey.

Yes everything seems to be working as it should now. Thanks for your help!

**Closed** 2022-06-23 16:25 UTC
