### ISSUE TITLE
add support for @defer and @stream directives

### ISSUE THREAD

**Issue by MarkLyck** [gqty-dev/gqty#857] opened 2022-05-01 18:11 UTC
I just recently stumbled across this library, and I LOVE IT!

It significantly improves the experience of querying data. But  I noticed 1 big downside of this vs apollo-client.

gqty doesn't seem to support the `@defer` or `@stream` directives.

@defer is something we heavily use in our application as one of our data-sources we query through graphQL can take several seconds to respond, while most of our other data-sources respond in <200ms. So we always try to @defer the slow data source when querying multiple sources in 1 request.

I haven't found a way to do this with gqty  :( and I don't see anything about it in the docs.

Please add support for `@defer` and maybe the `@stream` directives.

Apollo has had these features since 2018 (4 years now)

You can read more about it from this post from 2020: https://graphql.org/blog/2020-12-08-improving-latency-with-defer-and-stream-directives/

See apollo-server @defer implementation: https://www.apollographql.com/blog/community/backend/introducing-defer-in-apollo-server/

**Comment by vicary** [comment] 2022-07-05 06:00
Duplicate of #448, please chime in if you feel like adding more context into the discussion.

**Closed by vicary** 2022-07-05 06:00 UTC
