### ISSUE TITLE
basic query results in infinite loop (issue with pg_graphql)

### ISSUE THREAD

**Issue by cdaringe** [gqty-dev/gqty#520] opened 2022-01-08 23:47 UTC
# Problem

Using a basic query results in an infinite loop.

```jsx
import { useQuery } from "mfe-admin-gql-client";

export default function Home() {
  const query = useQuery({
    suspense: false,
  });
  if (query.$state.isLoading) return <p>Loading...</p>;
  return (
      <pre>
        {query.allMfes().edges?.map((e) => {
          return e.node.version; // 😵
        })}
      </pre>
  )
}
```

The network tab shows that each and every query completes successfully.

It is not repeatable on all APIs, but my API and project is very repeatable. Mentioned also in #314. Seems perhaps a cache lookup issue?

## Reproduction

Requires docker-compose

https://github.com/cdaringe/mfe-tools/tree/bug-demo#reproduction

**Comment by PabloSzx** [comment] 2022-01-08 23:51
thank you, I will take a look

**Comment by aitoraznar** [comment] 2022-01-11 16:18
We are experiencing this bug, can be related to this one?

https://github.com/wpengine/faustjs/issues/723

**Comment by PabloSzx** [comment] 2022-01-11 16:51
I've been trying to use the reproduction and it's unusable, I'm trying to modify the code and nothing changes, trying to modify mfe-admin-gql-client/src/generated/index.ts and nothings changes, adding console.logs, throwing errors, nothing gets executed, sorry, but invalid reproduction repo @cdaringe

**Comment by PabloSzx** [comment] 2022-01-11 16:53
> We are experiencing this bug, can be related to this one?
> 
> [wpengine/faustjs#723](https://github.com/wpengine/faustjs/issues/723)

I don't know, but as I mentioned, I need a valid reproduction repo

**Comment by cdaringe** [comment] 2022-01-11 17:33
@PabloSzx 

the client code must be rebuilt each each, `npm run build`, from the root or from the local dir. i didn't setup hot-code reloading in the reproduction

**Comment by PabloSzx** [comment] 2022-01-11 17:57
I tried rebuilding, I don't know if it's aggressive caching of parcel or something, but trust me I tried doing a lot of thing, but if I add console.log, rebuild everything, and the client side doesn't do anything, something is wrong with the reproduction :disappointed:

**Comment by cdaringe** [comment] 2022-01-11 18:50
Gotcha. I will investigate this evening and make sure there is a functional way to reflect changes.

**Comment by cdaringe** [comment] 2022-01-11 21:13
Ok, there were a few things that made debugging less intuitive :)

- make sure you are on the correct branch, for staters, `bug-demo`
- the `build` script was _purging_ the gqty code and regenerating it :),  Previously, it was`"build": "rm -rf src/generated && gqty generate && tsc"`. whoops! patched. it will not generate any more on build. you can just manually regenerate as needed by calling `gqty generate` from the `packages/mfe-admin-gql-client` folder _iff_ needed
- parcel was be _stripping_ `debugger` statements. how irritating! I added a terser config to _not_ drop `debugger` statements

patches here: https://github.com/cdaringe/mfe-tools/commit/d2d70d4cc35ea9561f5835a3ca017ac8545cd575

So, when you make changes, you can just run `npm build` from the root, and it will take

**Comment by PabloSzx** [comment] 2022-01-11 21:29
> Ok, there were a few things that made debugging less intuitive :)
> 
> * make sure you are on the correct branch,`bug-demo`
> * the `build` script was _purging_ the gqty code and regenerating it :),  Previously, it was`"build": "rm -rf src/generated && gqty generate && tsc"`. whoops! patched. it will not generate any more on build. you can just manually regenerate as needed by calling `gqty generate` from the `packages/mfe-admin-gql-client` folder _iff_ needed
> * parcel was _stripping_ `debugger` statements. how irritating! I added a terser config to _not_ drop `debugger` statements
> 
> patches here: [cdaringe/mfe-tools@d2d70d4](https://github.com/cdaringe/mfe-tools/commit/d2d70d4cc35ea9561f5835a3ca017ac8545cd575)
> 
> So, when you make changes, you can just run `npm build` from the root, and it will take. I followed my own instructions on a fresh clone, and these patches should make your expectations work :)

thank you :+1:

**Comment by PabloSzx** [comment] 2022-01-13 23:28
@cdaringe confirmed that this is an issue with the API not respecting the graphql alias, you can read about it here https://graphql.org/learn/queries/#aliases:


Check:

![image](https://user-images.githubusercontent.com/8672915/149424712-f6f0c0a2-bdd9-47ba-92d4-6d2772b0e550.png)
![image](https://user-images.githubusercontent.com/8672915/149424746-35eb5db9-7400-42e0-b68b-611d020faa65.png)

the graphql request clearly requires that allMfes is served in allMfes0, which is not what it's getting, gqty starts looping because it doesn't do validation on the API request, it just assumes the data is correct

**Comment by PabloSzx** [comment] 2022-01-13 23:37
created the issue in pg_graphql: https://github.com/supabase/pg_graphql/issues/40

**Comment by cdaringe** [comment] 2022-01-14 00:25
@PabloSzx super interesting, thank you for discovering and reporting that. I was right there and surprised I didn’t pick that up when looking at the other thread. Much appreciated

**Comment by olirice** [comment] 2022-01-14 14:45
@cdaringe this is fixed on master in pg_graphql
please try again when ready & lmk if you run into anything unexpected

**Closed** 2022-01-14 18:24 UTC
Labels: bug, bug-on-server-side

**Comment by aitoraznar** [comment] 2022-01-17 10:21
Hi @PabloSzx, thanks for your hard work. How can I apply this patch of "pg_graphql" in gqty? I'm not sure if it's a gqty thing or this has to be applied in the server-side (in my case wp-graphql for Wordpress).
Many thanks.

**Comment by PabloSzx** [comment] 2022-01-17 17:07
> Hi @PabloSzx, thanks for your hard work. How can I apply this patch of "pg_graphql" in gqty? I'm not sure if it's a gqty thing or this has to be applied in the server-side (in my case wp-graphql for Wordpress). Many thanks.

Yeah, it's not a gqty thing, it this issue appears in another environment different than pg_graphql we need a way to reproduce the issue
