### ISSUE TITLE
infinite render loop with data table components

### ISSUE THREAD

**Issue by cdreier** [gqty-dev/gqty#1588] opened 2023-05-09 15:09 UTC
Hi,

in version `3.0.0-alpha-1b4ddaba.0`  i am running in infinite render loops when using  https://v2.grommet.io/datatable or https://react-data-table-component.netlify.app/?path=/story/getting-started-intro--page 

the component renders over and over - when downgrading to `2.3.0` everything is working fine

```
import { DataTable, Text } from "grommet"
import { useQuery } from "../gqty"


const Start = () => {

  console.log("render loooop!")
  const q = useQuery()

  return (
    <div>
      <DataTable
        data={q.students()}
        columns={[
          {
            property: 'lastname',
            header: <Text>Name</Text>,
          },
        ]} />
    </div>
  )
}

```

**Comment by vicary** [comment] 2023-05-09 17:05
@cdreier Thanks again for reporting the issue.

I am not familiar with Grommet enough to create a minimum repo, it throws the following error when I try to add `<DataTable />`.

```
TypeError: defaultValidatorFn is not a function
```

Error | Source Code
:-: | :-:
![image](https://github.com/gqty-dev/gqty/assets/85772/e458cd14-f232-4d12-a068-ff21ef62953c) | ![image](https://github.com/gqty-dev/gqty/assets/85772/85e450a5-ff70-4454-a248-66fbc7a1c153)

Would you mind sharing a minimum reproducing repo?

**Comment by vicary** [comment] 2023-05-09 17:06
@cdreier Thanks again for reporting the issue.

I don't think I am familiar with Grommet enough, it throws the following error when I try to add `<DataTable />` in a freshly created next.js app.

```
TypeError: defaultValidatorFn is not a function
```

Error | Source Code
:-: | :-:
![image](https://github.com/gqty-dev/gqty/assets/85772/e458cd14-f232-4d12-a068-ff21ef62953c) | ![image](https://github.com/gqty-dev/gqty/assets/85772/85e450a5-ff70-4454-a248-66fbc7a1c153)

Would you mind sharing a minimum reproducing repo?

**Comment by vicary** [comment] 2023-05-10 11:24
`<DataTable />` is reading GQty's proxy outside of a render cycle, where GQty assumes to be a user interaction, e.g. button click, triggering another render.

@cdreier I tried replacing the re-render with a soft refetch in `3.0.0-alpha-d01132d2.0`, give it a try!

**Comment by cdreier** [comment] 2023-05-10 18:19
Hi @vicary - just tested the new release in my project and it is working pretty well now :)

thanks a lot!

**Comment by vicary** [comment] 2023-05-10 19:05
I'm closing this for now, feel free to reopen if it happens again!

**Comment by cdreier** [comment] 2023-05-11 19:24
Hi @vicary ,

i created a repo with another few strange bugs, also fetching loops in certain conditions - i am not sure if grommet is doing strange things, but with GQty 2.3 everything was working

i created a small graphql server where you can test against, and i added descriptions on the passengers page. 

short description of the issues

* every hover over a row, triggers a fetch from the server - even if the table does something with the proxy, there should be a cache? 
* there are strange dependencies between different `useQuery` hooks - it is hard to describe, so just open the passengers page and click one passenger with your network monitor open :rocket: 

https://github.com/cdreier/gqty_rendering

i really like the idea and philosophy behind GQty - feel free to ping me if you have other questions or if i can help at some point

**Comment by vicary** [comment] 2023-05-12 20:22
Hey @cdreier, I have reopened the issue. Replying your points below:

> every hover over a row, triggers a fetch from the server - even if the table does something with the proxy, there should be a cache?

The new cache defaults to a more aggressive SWR refetching. Try increasing the `maxAge` to something like 5 seconds, it would greatly reduce the fetching frequency. You may also put `maxAge: Infinity` to disable expiry.

> there are strange dependencies between different useQuery hooks - it is hard to describe, so just open the passengers page and click one passenger with your network monitor open 🚀

Passing child proxies upwards to parent would mess query scopes up a little bit, you may prop drilling from the parent `<Passengers data={query.passengers()}  />` to prevent this for now.

I'll figure out a way to force them into one single fetch, so they don't race with each other.

**Comment by cdreier** [comment] 2023-05-12 21:58
Hi @vicary  - you are right, it seems like for my usecases, a disabled cache expiry solves lots of problems! I try to dig a bit deeper during the weekend and provide more feedback :+1:

**Comment by vicary** [comment] 2023-05-13 13:09
@cdreier Ended up hashing all variable names to properly dedupe this, but with `alpha-4c58a180.0` I think the racing condition is gone now. Please feel free to give it a test, I'll wait for this one before announcing beta.

**Comment by cdreier** [comment] 2023-05-13 21:25
no changes for me with the default settings `maxAge: 0` - and even with `maxAge: 5000` it happens when you hover the modal and the cache refreshes - `maxAge: Infinity` was the only working solution for now 

[Bildschirmaufzeichnung vom 2023-05-13, 23-21-04.webm](https://github.com/gqty-dev/gqty/assets/731608/fefdabb3-e30f-46a6-9a25-77149cd6ae0b)

**Comment by cdreier** [comment] 2023-05-13 21:29
and i found another issue in the latest version with the cache normalization - the rerendering does not understandable things... when disabling the normalization, it is working

[Bildschirmaufzeichnung vom 2023-05-13, 23-27-11.webm](https://github.com/gqty-dev/gqty/assets/731608/36537e0b-2294-4f87-8ea2-cf0f0824a79c)

**Comment by vicary** [comment] 2023-05-14 04:43
Yes I can reproduce it, sorry for making a hasty fix and I should test it more thoroughly. Feels like it is triggered by something else, I'll take a look.

For the second one, with `updatedPassenger?.id` alone, mutation and normalization shouldn't work. A selection of *passenger.id* and *passenger.car.id* should be the minimum information for a normalized cache to update the reference.

I have tested with the old versions and the *car column in passenger table* is still not updating after clicking. What is the expected behaviour?

**Comment by cdreier** [comment] 2023-05-14 12:44
you are right, now i can see the same behaviour with the old version :confused: 

the expectation was, as shown without the cache normalization - the update runs, i can see in the network tab, that the data in the response is correct, and the view should update to the correct car name. I did not find a way to make it work with normalization, even if i fetch all the attributes from the updatedPassenger

**Comment by vicary** [comment] 2023-05-15 06:06
I am not sure how deep this is gonna get, let's go as far as we are comfortable with.

I'll show my investigation process below, let me know if you see anything else worth trying.

# Goal

Started a new repo and try to reproduce it bottom-up, the goal is to bisect my way to your repo to pin down the root cause.

Your API is returning empty arrays, so I am falling back to my toy API. Reduced the codebase a little bit, but keeping the fetch loop there.

https://github.com/vicary/gqty_rendering/blob/master/src/App.tsx

https://github.com/gqty-dev/gqty/assets/85772/1f16f5f1-9085-4b1f-bf74-755829619cc0

<details>
<summary>Click to see current progress</summary>

1. Rendering a data array with simple `<ol>`, it only triggers one more query and it is the expected behavior.

    https://github.com/gqty-dev/gqty/assets/85772/48b2c890-16df-4d92-bf53-68d8d9317c6f

2. Replacing the  `<ol>` with `<DataTable />`, still works.

    https://github.com/gqty-dev/gqty/assets/85772/926d478a-63b1-4865-ac0a-71da9c6b980d

3. Adding `onClickRow`, this is where it re-renders on hover. Fetches are firing from my cursor movements, but it's not looping.

    https://github.com/gqty-dev/gqty/assets/85772/4b1d2e82-4550-45cb-bc92-0e3ccb593a21

4. Adding `hpe` theme, still no avail.

    https://github.com/gqty-dev/gqty/blob/feat/scoped-query/examples/gnt/app/backflow/page.tsx

    https://github.com/gqty-dev/gqty/assets/85772/6d5e0a32-54b2-42f0-afd4-ce9001adf69d

</details>

**Comment by vicary** [comment] 2023-05-15 07:56
@cdreier Both minreps are no longer looping with `alpha-524ea531.0`, we can move on to the mutation issue when you confirm it working.

**Comment by cdreier** [comment] 2023-05-15 15:18
@vicary i am a bit short in time, but i discovered one thing: it only loops (still) when a proxy is used in the modal!

here, i am using ` {activePassenger?.name}` - if i remove the name, no loops happen

```
{modalOpen && (<Layer position={'top'} onEsc={() => setModalOpen(false)} >
        <Box pad="medium" gap="medium" overflow="auto">
          <h1>assign {activePassenger?.name}</h1>
          <Cars onClick={c => {
            updatePassenger({
              args: {
                carID: c?.id,
              }
            })
          }} />
        </Box>
      </Layer >)}
```

**Comment by vicary** [comment] 2023-05-16 15:58
With `alpha-085ddbf4.0` your repo is no longer looping, moving on to mutations.

So when you're querying two lists, refetching is the only way.

There are two top-level cache key at play:

1. `query.cars`, and
2. `query.passengers`

When you update the car of a passenger, you can only query the new car, thus update its population, leaving the population of the old car dangling/stale.

We have no way to directly update the top level cache key `query.cars`, when you re-render the cars list it'll always be incorrect. Post-mutation refetching is required in this scenario.

> i am a bit short in time

I'll leave this open until Friday, you may leave a comment afterwards here if you're still hitting anything.

**Comment by cdreier** [comment] 2023-05-17 06:34
i can confirm, no more loops! :rocket:

**Closed** 2023-05-18 05:28 UTC
